gpath = { db = {  }, net = {  } }
gpath.db.ucf101_rgb_s1 = '/home/dgyoo/workspace/datain/UCF101_25FPS/'
gpath.db.ucf101_of_s1 = '/home/dgyoo/workspace/datain/UCF101_25FPS/'
gpath.db.ucf101_rgb_s2 = '/home/dgyoo/workspace/datain/UCF101_25FPS/'
gpath.db.ucf101_of_s2 = '/home/dgyoo/workspace/datain/UCF101_25FPS/'
gpath.db.ucf101_rgb_s3 = '/home/dgyoo/workspace/datain/UCF101_25FPS/'
gpath.db.ucf101_of_s3 = '/home/dgyoo/workspace/datain/UCF101_25FPS/'
gpath.net.alex_caffe_model = '/home/dgyoo/workspace/net/caffe/bvlc_alexnet.caffemodel'
gpath.net.alex_caffe_proto = '/home/dgyoo/workspace/net/caffe/bvlc_alexnet_deploy.prototxt'
gpath.net.vggm_caffe_model = '/home/dgyoo/workspace/net/caffe/VGG_CNN_M_2048.caffemodel'
gpath.net.vggm_caffe_proto = '/home/dgyoo/workspace/net/caffe/VGG_CNN_M_2048_deploy.prototxt'
gpath.net.vgg16_caffe_model = '/home/dgyoo/workspace/net/caffe/VGG_ILSVRC_16_layers.caffemodel'
gpath.net.vgg16_caffe_proto = '/home/dgyoo/workspace/net/caffe/VGG_ILSVRC_16_layers_deploy.prototxt'
gpath.dataout = '/home/dgyoo/workspace/dataout/diffnet'
