gpath = { db = {  }, net = {  } }
gpath.db.ucf101 = '/home/dgyoo/workspace/datain/UCF101FRAME/'
gpath.net.alex_caffe_model = '/home/dgyoo/workspace/net/caffe/bvlc_alexnet.caffemodel'
gpath.net.alex_caffe_proto = '/home/dgyoo/workspace/net/caffe/bvlc_alexnet_deploy.prototxt'
gpath.net.vggm_caffe_model = '/home/dgyoo/workspace/net/caffe/VGG_CNN_M_2048.caffemodel'
gpath.net.vggm_caffe_proto = '/home/dgyoo/workspace/net/caffe/VGG_CNN_M_2048_deploy.prototxt'
gpath.net.vgg16_caffe_model = '/home/dgyoo/workspace/net/caffe/VGG_ILSVRC_16_layers.caffemodel'
gpath.net.vgg16_caffe_proto = '/home/dgyoo/workspace/net/caffe/VGG_ILSVRC_16_layers_deploy.prototxt'
gpath.net.res18_torch_model = '/home/dgyoo/workspace/net/torch/resnet-18.t7'
gpath.net.res34_torch_model = '/home/dgyoo/workspace/net/torch/resnet-34.t7'
gpath.net.res50_torch_model = '/home/dgyoo/workspace/net/torch/resnet-50.t7'
gpath.net.res101_torch_model = '/home/dgyoo/workspace/net/torch/resnet-101.t7'
gpath.net.res152_torch_model = '/home/dgyoo/workspace/net/torch/resnet-152.t7'
gpath.dataout = '/home/dgyoo/workspace/dataout/diffnet'
