gpath = { db = {  }, net = {  } }
gpath.db.ucf101_rgb_s1 = '/mnt/ssd/tmp/jolee/ch/'
gpath.db.ucf101_of_s1 = '/mnt/ssd/tmp/jolee/ch/'
gpath.db.ucf101_rgb_s2 = '/mnt/ssd/tmp/jolee/ch/'
gpath.db.ucf101_of_s2 = '/mnt/ssd/tmp/jolee/ch/'
gpath.db.ucf101_rgb_s3 = '/mnt/ssd/tmp/jolee/ch/'
gpath.db.ucf101_of_s3 = '/mnt/ssd/tmp/jolee/ch/'
gpath.net.alex_caffe_model = '/mnt/ilcompf2d1/user/jolee/research/net/caffe/bvlc_alexnet.caffemodel'
gpath.net.alex_caffe_proto = '/mnt/ilcompf2d1/user/jolee/research/net/caffe/bvlc_alexnet_deploy.prototxt'
gpath.net.vggm_caffe_model = '/mnt/ilcompf2d1/user/jolee/research/net/caffe/VGG_CNN_M_2048.caffemodel'
gpath.net.vggm_caffe_proto = '/mnt/ilcompf2d1/user/jolee/research/net/caffe/VGG_CNN_M_2048_deploy.prototxt'
gpath.net.vgg16_caffe_model = '/mnt/ilcompf2d1/user/jolee/research/net/caffe/VGG_ILSVRC_16_layers.caffemodel'
gpath.net.vgg16_caffe_proto = '/mnt/ilcompf2d1/user/jolee/research/net/caffe/VGG_ILSVRC_16_layers_deploy.prototxt'
gpath.dataout = '/mnt/ilcompf2d1/user/jolee/research/diffnet_dataout/'
